### ISSUE TITLE
[TASK][Edit an existing contact in a dialog] adapt the contact edit template

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-contacts#109]
[STORY](https://app.zenhub.com/workspaces/ft---calendar--contacts-dev-5ff3db9704b1b3001295e51f/issues/openpaas-suite/esn-frontend-contacts/93)

## note:
we are going to reuse the contact creation template implemented in [here](https://app.zenhub.com/workspaces/ft---calendar--contacts-dev-5ff3db9704b1b3001295e51f/issues/openpaas-suite/esn-frontend-contacts/107)

### TODO:
* [x] remove the  `contactEditSubheader` directive and its files ( ie src/linagora.esn.contact/app/contact/edit/contact-edit-subheader.pug etc...)
* [x] adapt the `editContactController` to have the same handler name as the one described in the template ( 1 button calls the same function name but in 2 different controllers )
*This allows us to use the same template without changing much*

**Comment by asmaNode** [comment]
https://github.com/OpenPaaS-Suite/esn-frontend-contacts/pull/134
