### ISSUE TITLE
[TASK] Change default address book invite status to accepted

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-contacts#113]
When sharing an address book to someone, the sharing should be automatically displayed in delegate view.

In Sabre, shared address book objects have an invite-status property.
It should be set to ACCEPTED when adding a delegation

* Related Story *

[[STORY] When sharing addressbook, it should be automatically added to the user view](https://github.com/OpenPaaS-Suite/esn-frontend-contacts/issues/112)

**Comment by huy-ta** [comment]
Here's the PR: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/301.
