### ISSUE TITLE
Unable to subscribe to shared address book

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-contacts#33]
Steps to reproduce:
1. Go to https://dev.open-paas.org/contacts/
2. Click (+) button on the left menu and select "Shared address book" option

Expected result:
"Shared address book" popup is displayed and user can search for other users and select address books to subscribe

Actual result:

There is no field to search for user 
![20200821_1](https://user-images.githubusercontent.com/53081477/90849580-c900dd80-e399-11ea-92c8-35032e8e1a5c.png)

Linked PR: https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/100

**Comment by huy-ta** [comment]
@piavgh Please write a simple DoD like [this one](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/74#issuecomment-678178312) and then @ one of the members of the QA team (preferrably the author of the issue) so that he/she can receive a mail notification.

**Comment by piavgh** [comment]
## DoD:

User should be able to select other users to subscribe to their address book

Environment tested
- Browser: Chrome, Firefox (Desktop - Ubuntu)
- Mode: Dev

@hantt12 : please verify this. Thanks

**Comment by tlle14** [comment]
Hi @piavgh 

Retest failed!

I can see the text field but there's no shared contact displaying for the email.

![image](https://user-images.githubusercontent.com/69950655/92068133-48e26b00-edd0-11ea-9c50-6d0fcdcadcde.png)

**Comment by piavgh** [comment]
@tlle14 : can you please check to see if that user shared any address book? If not, this is the correct behaviour

**Comment by tlle14** [comment]
> @tlle14 : can you please check to see if that user shared any address book? If not, this is the correct behaviour

Hi @piavgh 

UserA is sharing contact with public right is "See all contacts"
