### ISSUE TITLE
Followed members address book is not shown

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-contacts#35]
Steps to reproduce:

1. As admin, enable Followed member address book in adminstration
2. User go to https://dev.open-paas.org/contacts/
3. Check if Followed member is shown in the left menu under Directory section

Expected result:
Followed members is listed in Directory. When user clicks on Followed members, the list of followed members is shown on the right panel

Actual result:
Followed member address book is not in the left menu

![20200821_2](https://user-images.githubusercontent.com/53081477/90851236-44648e00-e39e-11ea-845d-3a8ca6d5fd78.png)

---

**EDIT**:

![Screenshot 2020-09-07 17:08:27](https://user-images.githubusercontent.com/4060207/92376462-d30e3480-f12c-11ea-9d92-4311a6933cee.png)

So we will need to remove everything related to `follow` in modules `admin`, `contacts`, ...

**Comment by tuanlc** [comment]
The question is: Do we continue to support `follow` feature? cc @MichaelBailly

**Comment by hantt12** [comment]
> The question is: Do we continue to support `follow` feature? cc @MichaelBailly

I don't think there is anyway to follow users now because we no longer have Chat and Community. But still, we need to wait for Michael's confirmation on the removing of Followed Member on Contact page

**Comment by piavgh** [comment]
@hantt12 : please check my edit on the description and proceed this issue further (maybe close it)

**Comment by tlle14** [comment]
Hi @piavgh 

I confirmed to close this issue.

**Comment by tlle14** [comment]
I created a new ticket related to the "EDIT" part

https://github.com/OpenPaaS-Suite/esn-frontend-account/issues/65
