### ISSUE TITLE
UI/Create new address book/Placeholder is still shown when user inputs the address book name

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-contacts#36]
See screenshot

![20200821_3](https://user-images.githubusercontent.com/53081477/90864820-92d45580-e3bb-11ea-9de3-e74699e7fb9d.png)

**Comment by pbson** [comment]
Could you have a look again at this issue. I couldn't be able to reproduce the bug. Thank you

**Comment by tlle14** [comment]
Hi @pbson 

I can reproduce it easily

![image](https://user-images.githubusercontent.com/69950655/92580854-1c8b8a80-f2b9-11ea-8280-52761b9c1ee6.png)

**Comment by huy-ta** [comment]
@pbson Please write a DoD for this.

**Comment by huy-ta** [comment]
I've confirmed that the issue has been fixed on https://dev.open-paas.org/contacts/ and https://openpaas.linagora.com/contacts/, both on mobile and desktop devices.

**Comment by tlle14** [comment]
thank @huy-ta 

Retest pass!

![Peek 2020-09-17 18-12](https://user-images.githubusercontent.com/69950655/93463092-758a9c80-f911-11ea-9c27-9e63791c377f.gif)
