### ISSUE TITLE
Translation/Collected contact list is not translated 

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-contacts#37]
![20200821_2](https://user-images.githubusercontent.com/53081477/90869049-e2b61b00-e3c1-11ea-8813-8cd717b8f219.png)
![20200821_3](https://user-images.githubusercontent.com/53081477/90869540-90292e80-e3c2-11ea-8a69-ac9621b45437.png)

![20200821](https://user-images.githubusercontent.com/53081477/90869062-e5187500-e3c1-11ea-9c57-7db5093c327e.png)
![20200821_5](https://user-images.githubusercontent.com/53081477/90869698-c8c90800-e3c2-11ea-9ee4-b4fd11faeb3d.png)

**Comment by huy-ta** [comment]
I cannot reproduce the issue anymore. Can you confirm and close the issue? @tlle14
