### ISSUE TITLE
Translation: Subscribe address book popup is not in the right language

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-contacts#38]
when the language is Russia, popup is displayed in Chinese:

![20200821_2](https://user-images.githubusercontent.com/53081477/90869202-198c3100-e3c2-11ea-85e6-b334d7b7ed99.png)

When the selected language is Vietnamese, popup is displayed in English

![20200821_4](https://user-images.githubusercontent.com/53081477/90869435-6b34bb80-e3c2-11ea-9bc0-ba3468819014.png)

When selected language is French, popup is displayed in Chinese
![20200821_6](https://user-images.githubusercontent.com/53081477/90869864-07f75900-e3c3-11ea-98fc-49b063b62eaa.png)

**Comment by asmaNode** [comment]
@hantt12  this bug is unreproducible
