### ISSUE TITLE
Translation/Copy contact popup should be in French instead of Chinese

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-contacts#39]
![20200821_7](https://user-images.githubusercontent.com/53081477/90871135-c9fb3480-e3c4-11ea-8b4f-f6c67a29ef6b.png)

**Comment by huy-ta** [comment]
It is also wrong for the other languages as well.

**Comment by asmaNode** [comment]
@hantt12 are you sure that the bug still persist i had test it with different language and it is working

**Comment by asmaNode** [comment]
![bug35conatct](https://user-images.githubusercontent.com/43316837/102601597-aea8f780-4120-11eb-91de-d27ad632068e.png)
