### ISSUE TITLE
Mobile/Tablet > Cannot upload a profile picture when creating a new contact

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-contacts#46]
**Actual Result**

When tap to "add a profile picture" button, nothing happens

![IMG_0102](https://user-images.githubusercontent.com/69950655/91545642-7f8d3100-e94b-11ea-9ab8-aeaf2751bd52.PNG)

**Expected result**

It should be able to upload a profile picture

**Environment**

- Mobile: iphone 7
- Tablet: ipad air 2

**Comment by tuanlc** [comment]
This issue is not only on mobile but also on desktop

**Comment by tuanlc** [comment]
### Definition Of Done
- Done: The bug was fixed on desktop and mobile
- Impact: Create/Edit contacts

**Comment by tlle14** [comment]
Thank @tuanlc 

Retest pass on DEV environment on iPhone, iPad, and Desktop.
