### ISSUE TITLE
Collected contact book isn't valid

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-contacts#51]
**Actual Result**

Collected contact is a default addressbook. It is displaying with an invalid icon and unable to open its setting.

![collected_contact](https://user-images.githubusercontent.com/69950655/92069264-1e45e180-edd3-11ea-9a3b-6ec3e0c0ec57.gif)

**Expected result**

Collected contact addressbook should be valid

**Comment by piavgh** [comment]
The reason for this issue is that in module `esn-frontend-contacts`, we don't have `linagora.esn.contact.collect`

**Comment by piavgh** [comment]
@MichaelBailly: please check my question above

**Comment by tuanlc** [comment]
I think it was missed. We should bring it back.

**Comment by tlle14** [comment]
Thank @piavgh 

Retest pass on DEV environment

![image](https://user-images.githubusercontent.com/69950655/92578967-cc132d80-f2b6-11ea-9056-cce7dcace63d.png)
