### ISSUE TITLE
After created, user need to refresh the page to see a new addressbook

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-contacts#74]
# Actual Result

![Peek 2020-09-17 18-12](https://user-images.githubusercontent.com/69950655/93463341-d1edbc00-f911-11ea-8d0b-06d0b7d4053c.gif)

# Expected Result

After creating a new addressbook, it should display in the sidebar menu without page refreshing

**Comment by tuanlc** [comment]
Hey @tlle14 
I cannot reproduce the bug on both production & dev platform

Please re-test.

**Comment by tlle14** [comment]
Thank @tuanlc 

The issue is no longer existing
