### ISSUE TITLE
There is no loading indicator when contacts are being loaded

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-contacts#96]
#### Steps to reproduce

- Login and go to Contacts
- Select an address book

#### Current behaviour

While the contacts in the selected address book are being loaded, a blank page is shown with nothing to indicate that the contacts are being loaded.

#### Expected behaviour

While the contacts in the selected address book are being loaded, there should be an OpenPaaS loading spinner at the center of the section to display contacts.

**Comment by asmaNode** [comment]
The bug is not persisting in dev plz check demo : https://images.zenhubusercontent.com/278394200/f55fd4f5-3d85-4f7e-95df-ec781885cc76/loader.mp4
