### ISSUE TITLE
The avatar and the name in a contact card are not aligned properly

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-contacts#99]
#### Current behaviour

The avatar and the name in a contact card are not aligned properly.

![image](https://user-images.githubusercontent.com/24670327/109275698-aa4b3a00-7847-11eb-8522-bee3a9f7d2ea.png)

![image](https://user-images.githubusercontent.com/24670327/109275929-fb5b2e00-7847-11eb-8665-fe67cd4b5c3c.png)

#### Expected behaviour

The avatar and the name in a contact card are aligned properly (vertically centered).

![image](https://user-images.githubusercontent.com/24670327/109275572-81c34000-7847-11eb-8e41-a2492ea1f3f3.png)

![image](https://user-images.githubusercontent.com/24670327/109276074-26de1880-7848-11eb-9825-882cd48d4814.png)

**Comment by asmaNode** [comment]
The bug does not persist anymore with the last corrections
https://images.zenhubusercontent.com/278394200/853943cb-bf04-4be4-837b-8068b46f4b69/align_user_in_middle.mp4
